apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "r-shiny-app.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - demo.azure.com
    secretName: ingress-tls-csi
  rules:
  - host: demo.azure.com
    http:
      paths:
      - path: /(.*)
        pathType: Prefix      
        backend:
          service:
            name: {{ include "r-shiny-app.fullname" . }}
            port:
              number: 80