kind: Service
apiVersion: v1
metadata:
  name: r-shiny-app
spec:
  type: NodePort
  selector:
    run: r-shiny-app
  ports:
  - protocol: TCP
    port: 3838
    targetPort: 3838
---
apiVersion: v1
kind: Service
metadata:
  name: r-shiny-app-load-balancer
spec:
  type: LoadBalancer
  ports:
  - port: 3838
  selector:
    run: r-shiny-app